### ISSUE TITLE
[Bug]: Fail to load correctly

### ISSUE THREAD

**Issue by Null-Ification** [gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon#54]
### Minecraft Version

1.20.1

### Mod Loader and Version

Forge-47.2.0

### Ad Astra! Version

1.15.16

### Addon Mod Version (This Mod)

5.8

### The details

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-02-13 02:08:33
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.0-universal.jar%23251!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.2.0-universal.jar%23251!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.2.0-universal.jar%23251!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[Tech.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ad_astra_giselle_addon.common.AdAstraGiselleAddon.initializeCommon(AdAstraGiselleAddon.java:65) ~[Ad-Astra-Giselle-Addon-forge-1.20.1-5.8.jar%23202!/:forge-1.20.1-5.8] {re:classloading}
-- MOD ad_astra_giselle_addon --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23248!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23247!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: where it should been
	Failure message: Ad Astra: Giselle Addon (ad_astra_giselle_addon) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 5.8
	Mod Issue URL: https://github.com/gisellevonbingen/Minecraft-Ad-Astra-Giselle-Addon/issues
	Exception message: java.lang.NoClassDefFoundError: Could not initialize class ad_astra_giselle_addon.common.registry.AddonBlocks
Stacktrace:
	at ad_astra_giselle_addon.common.AdAstraGiselleAddon.initializeCommon(AdAstraGiselleAddon.java:65) ~[Ad-Astra-Giselle-Addon-forge-1.20.1-5.8.jar%23202!/:forge-1.20.1-5.8] {re:classloading}
	at ad_astra_giselle_addon.common.AdAstraGiselleAddonForge.<init>(AdAstraGiselleAddonForge.java:21) ~[Ad-Astra-Giselle-Addon-forge-1.20.1-5.8.jar%23202!/:forge-1.20.1-5.8] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.2.0.jar%23248!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.0.jar%23247!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 502903032 bytes (479 MiB) / 1006632960 bytes (960 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
	Identifier: Intel64 Family 6 Model 69 Stepping 1
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 1.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics Family
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0a16
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4531
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 20.31
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 20.31
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 22004.36
	Virtual memory used (MB): 7815.76
	Swap memory total (MB): 15944.47
	Swap memory used (MB): 901.69
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		tetra-1.20.1-6.1.0.jar                            |tetra                         |tetra                         |6.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		AdvancedPeripherals-1.20.1-0.7.36r.jar            |Advanced Peripherals          |advancedperipherals           |0.7.36r             |COMMON_SET|Manifest: NOSIGNATURE
		open-parties-and-claims-forge-1.20.1-0.20.4.jar   |Open Parties and Claims       |openpartiesandclaims          |0.20.4              |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.3.1.jar                   |GeckoLib 4                    |geckolib                      |4.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.2.jar                   |Botarium                      |botarium                      |2.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.1.jar                     |Just Enough Items             |jei                           |15.3.0.1            |COMMON_SET|Manifest: NOSIGNATURE
		create_recycle_1.0.2_forge_1.20.1.jar             |Create Recycling              |create_crush_everything       |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.0.jar                          |Placebo                       |placebo                       |8.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		mobhealthbar-forge-1.20.x-2.3.0.jar               |YDM's Mob Health Bar          |mobhealthbar                  |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		alternate_current-mc1.20-1.7.0.jar                |Alternate Current             |alternate_current             |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.2.jar                       |MixinExtras                   |mixinextras                   |0.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		weather2-1.20.1-2.8.2.jar                         |Weather2                      |weather2                      |1.20.1-2.8.2        |COMMON_SET|Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		tl_skin_cape_forge_1.20_1.20.1-1.32.jar           |TLSkinCape                    |tlskincape                    |1.32                |COMMON_SET|Manifest: ef:fe:e7:59:91:bb:3a:06:c1:94:f4:f3:9c:3e:26:69:47:fa:2e:c5:53:d3:38:21:65:cc:04:75:e7:61:19:40
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		emi-1.1.0+1.20.1+forge.jar                        |EMI                           |emi                           |1.1.0+1.20.1+forge  |COMMON_SET|Manifest: NOSIGNATURE
		HostileNeuralNetworks-1.20.1-5.2.1.jar            |Hostile Neural Networks       |hostilenetworks               |5.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		ToolBelt-1.20-1.20.0.jar                          |Tool Belt                     |toolbelt                      |1.20.0              |COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.20.1-10.0.0-169.jar        |Immersive Engineering         |immersiveengineering          |1.20.1-10.0.0-169   |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		Jade-1.20.1-forge-11.8.0.jar                      |Jade                          |jade                          |11.8.0              |COMMON_SET|Manifest: NOSIGNATURE
		appliedenergistics2-forge-15.0.20.jar             |Applied Energistics 2         |ae2                           |15.0.20             |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.7.0+1.20.1.jar                     |Curios API                    |curios                        |5.7.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.5.19.jar                     |Mekanism                      |mekanism                      |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismWeapons-1.20.1-1.3.jar                    |Mekanism: Weapons             |mekaweapons                   |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.5.19.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		ars_nouveau-1.20.1-4.9.0-all.jar                  |Ars Nouveau                   |ars_nouveau                   |4.9.0               |COMMON_SET|Manifest: NOSIGNATURE
		MekanismAdditions-1.20.1-10.4.5.19.jar            |Mekanism: Additions           |mekanismadditions             |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.20.1-6.1.1.jar                            |mutil                         |mutil                         |6.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.7_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.9.7              |COMMON_SET|Manifest: NOSIGNATURE
		[1.20.1] SecurityCraft v1.9.8.jar                 |SecurityCraft                 |securitycraft                 |1.9.8               |COMMON_SET|Manifest: NOSIGNATURE
		FluxNetworks-1.20.1-7.2.0.14.jar                  |Flux Networks                 |fluxnetworks                  |7.2.0.14            |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughMekanismMultiblocks-1.20.1-4.2.jar      |Just Enough Mekanism Multibloc|jei_mekanism_multiblocks      |4.2                 |COMMON_SET|Manifest: NOSIGNATURE
		buildinggadgets2-1.0.6.jar                        |Building Gadgets 2            |buildinggadgets2              |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.22.jar            |Resourceful Lib               |resourcefullib                |2.1.22              |COMMON_SET|Manifest: NOSIGNATURE
		coroutil-forge-1.20.1-1.3.7.jar                   |CoroUtil                      |coroutil                      |1.20.1-1.3.7        |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.5.19.jar                |Mekanism: Tools               |mekanismtools                 |10.4.5              |COMMON_SET|Manifest: NOSIGNATURE
		constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.1.13-forge.jar                     |Architectury                  |architectury                  |9.1.13              |COMMON_SET|Manifest: NOSIGNATURE
		ae2wtlib-15.2.1-forge.jar                         |AE2WTLib                      |ae2wtlib                      |15.2.1-forge        |COMMON_SET|Manifest: NOSIGNATURE
		cc-tweaked-1.20.1-forge-1.109.5.jar               |CC: Tweaked                   |computercraft                 |1.109.5             |COMMON_SET|Manifest: NOSIGNATURE
		JadeAddons-1.20.1-forge-5.2.2.jar                 |Jade Addons                   |jadeaddons                    |5.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		Applied-Mekanistics-1.4.2.jar                     |Applied Mekanistics           |appmek                        |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.16.jar                 |Ad Astra                      |ad_astra                      |1.15.16             |COMMON_SET|Manifest: NOSIGNATURE
		Ad-Astra-Giselle-Addon-forge-1.20.1-5.8.jar       |Ad Astra: Giselle Addon       |ad_astra_giselle_addon        |5.8                 |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: bbe5fee7-e977-4811-8bb7-d550b289e2e5
	FML: 47.2
	Forge: net.minecraftforge:47.2.0
	Flywheel Backend: GL33 Instanced Arrays

**Comment by Null-Ification** [comment]
I don't know why this happened but Ad Astra's new(?) update(?) broke it, they added a few things that this mod has.
like, sneak-click a door with an Ad Astra wrench will lock/unlock the door.

**Comment by gisellevonbingen** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon/files/5047970
Update to latest version please.

**Comment by Null-Ification** [comment]
![image](https://github.com/gisellevonbingen-Minecraft/Ad-Astra-Giselle-Addon/assets/154444578/e7b18b1d-88c5-4627-bfdf-a355ffc6735e)
ok, now it makes sense.
sorry for wasting your time
